name: Node.js CI

on:
  push:
    branches: [main, develop, feature/**]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: [macos-latest, ubuntu-latest, windows-latest]

    strategy:
      matrix:
        node-version: [12.22.x, 14.17.x, 16.3.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
